version: "3.8"

services:
    app:
        build: .
        ports:
            - "8000:8000"
        environment:
            - NODE_ENV=production
            - MONGO_URL=mongodb://mongo:27017/yourdbname
        depends_on:
            - mongo
        networks:
            - app-network

    mongo:
        image: mongo:4.2
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
        networks:
            - app-network

    mongo-express:
        image: mongo-express:0.54
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=example
            - ME_CONFIG_MONGODB_SERVER=mongo
        depends_on:
            - mongo
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mongo-data:
